// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6SvToq-UwYgCN91rEOaG_Rl9dIvmD160',
    appId: '1:517098062644:web:2535079fa70bfc59375b61',
    messagingSenderId: '517098062644',
    projectId: 'cwikadmin',
    authDomain: 'cwikadmin.firebaseapp.com',
    storageBucket: 'cwikadmin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3F-1HlIqUsxbNRwIIPhdX8O6hJ7S91IM',
    appId: '1:517098062644:android:2307f65b0c107fe3375b61',
    messagingSenderId: '517098062644',
    projectId: 'cwikadmin',
    storageBucket: 'cwikadmin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-x88gHTKISbAODF5fVzKt8andOa84FaY',
    appId: '1:517098062644:ios:d5c47949d16da4e3375b61',
    messagingSenderId: '517098062644',
    projectId: 'cwikadmin',
    storageBucket: 'cwikadmin.appspot.com',
    iosClientId: '517098062644-6mp86amg6th46qi2j77f8pb8dq1v2ia4.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwikapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-x88gHTKISbAODF5fVzKt8andOa84FaY',
    appId: '1:517098062644:ios:d5c47949d16da4e3375b61',
    messagingSenderId: '517098062644',
    projectId: 'cwikadmin',
    storageBucket: 'cwikadmin.appspot.com',
    iosClientId: '517098062644-6mp86amg6th46qi2j77f8pb8dq1v2ia4.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwikapp',
  );
}
